### ISSUE TITLE
Doesn't start on Fedora 36 (NVidia, X.org)

### ISSUE THREAD

**Issue by the-Mitu** [flathub/org.musescore.MuseScore#93] opened 2022-05-15 16:55 UTC
Currently MuseScore flatpak seems not to start on my Fedora 36 on X.org under NVidia graphics. When run from terminal (appended `-d` for more data), I see this:

```
Gtk-Message: 18:54:02.959: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:54:02.959: Failed to load module "pk-gtk-module"
Gtk-Message: 18:54:02.959: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:54:02.959: Failed to load module "pk-gtk-module"
unknown:unknown: Qt: Session management error: None of the authentication protocols specified are supported
unknown:unknown: global share: </app/share/mscore-3.6/>
unknown:unknown: configured localeName <system>
unknown:unknown: real localeName <pl_PL>
unknown:unknown: load translator </app/share/mscore-3.6/locale/mscore_pl_PL>
unknown:unknown: load translator </app/share/mscore-3.6/locale/instruments_pl_PL>
unknown:unknown: load translator </app/share/mscore-3.6/locale/tours_pl_PL>
unknown:unknown: load translator <qt_pl_PL> from </usr/translations>
unknown:unknown: read shortcuts from <:/data/shortcuts.xml>
```

I've tried `unset SESSION_MANAGER`, as found by googling the session management error – the line indeed disappeared, but the applicaiton didn't start anyway.

**Comment by hfiguiere** [comment] 2022-05-16 13:42
are you sure it is not the same is #80 ?  ie it is crashing.

**Comment by hfiguiere** [comment] 2022-05-16 13:43
most of the messages you see are red-herring cause by bad programing practices.

**Comment by Mormacill** [comment] 2022-06-20 22:02
Same problem here, same configuration, same error as @the-Mitu.

**Comment by the-Mitu** [comment] 2022-06-21 07:53
For some reason [this](https://github.com/flathub/org.musescore.MuseScore/issues/80#issuecomment-968358122) helped.

**Comment by hfiguiere** [comment] 2022-06-21 21:42
dupe of #80

**Closed by hfiguiere** 2022-06-21 21:42 UTC
